#!/usr/bin/env python3
"""Rasterise a TTF into an 8-bit alpha atlas plus a C table.

Georgia at 42 px is what the board ships. Baskerville was tried first — an
18th-century English typeface, about as close to Hamlet's printing tradition as
the system font list gets — and dissolved at this pixel density; Georgia was
drawn for screen legibility and holds.

The defaults here are the shipped ones, so running this with no arguments
reproduces the committed font_data.c.

The output is plain C data so the exact same glyph blitter runs in the host
preview and on the ESP32, with no font engine on either side. ~30 KB of flash.

The tokeniser in corpus/hamlet.py is `[A-Za-z']+|[.,!?;:—\\-]`, so the em dash
(U+2014) has to be in here alongside printable ASCII. It gets the slot right
after '~' rather than a real codepoint map, since it is the only non-ASCII
character the corpus can produce.

    python3 tools/mkfont.py --size 42
"""
from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent

FIRST, LAST = 32, 126           # printable ASCII
EM_DASH = "—"
CHARS = [chr(c) for c in range(FIRST, LAST + 1)] + [EM_DASH]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--font", default="/System/Library/Fonts/Supplemental/Georgia.ttf")
    ap.add_argument("--index", type=int, default=0)
    ap.add_argument("--size", type=int, default=42)
    ap.add_argument("--out", type=Path,
                    default=REPO / "firmware" / "components" / "wormrender" / "font_data.c")
    args = ap.parse_args()

    font = ImageFont.truetype(args.font, args.size, index=args.index)
    ascent, descent = font.getmetrics()

    # Rasterise each glyph tightly, then shelf-pack into one atlas.
    glyphs = []
    for ch in CHARS:
        box = font.getbbox(ch)
        w, h = max(1, box[2] - box[0]), max(1, box[3] - box[1])
        img = Image.new("L", (w + 4, h + 4), 0)
        ImageDraw.Draw(img).text((-box[0] + 2, -box[1] + 2), ch, font=font, fill=255)
        bbox = img.getbbox()
        if bbox is None:  # space and friends
            glyphs.append((ch, None, 0, 0, 0, 0, int(font.getlength(ch))))
            continue
        crop = img.crop(bbox)
        # bearing relative to the pen position sitting on the baseline
        bx = box[0] + bbox[0] - 2
        by = box[1] + bbox[1] - 2 - ascent
        glyphs.append((ch, crop, crop.width, crop.height, bx, by, int(font.getlength(ch))))

    atlas_w = 256
    x = y = row_h = 0
    placed = []
    for ch, crop, w, h, bx, by, adv in glyphs:
        if crop is None:
            placed.append((ch, 0, 0, 0, 0, bx, by, adv))
            continue
        if x + w > atlas_w:
            x = 0
            y += row_h
            row_h = 0
        placed.append((ch, x, y, w, h, bx, by, adv))
        row_h = max(row_h, h)
        x += w
    atlas_h = y + row_h

    atlas = Image.new("L", (atlas_w, atlas_h), 0)
    for (ch, crop, w, h, *_), (_, ax, ay, *_rest) in zip(glyphs, placed):
        if crop is not None:
            atlas.paste(crop, (ax, ay))

    data = atlas.tobytes()

    lines = [
        "// Generated by tools/mkfont.py — do not edit.",
        f"// {Path(args.font).name} @ {args.size}px, {len(CHARS)} glyphs, "
        f"{atlas_w}x{atlas_h} alpha atlas ({len(data)} B).",
        "//",
        "// Slot 0 is ' ' (0x20); slot 95 is the em dash U+2014, which the Hamlet",
        "// tokeniser emits and which is the only non-ASCII character it can produce.",
        "",
        '#include "wormrender.h"',
        "",
        f"const int wr_font_atlas_w = {atlas_w};",
        f"const int wr_font_atlas_h = {atlas_h};",
        f"const int wr_font_size = {args.size};",
        f"const int wr_font_ascent = {ascent};",
        f"const int wr_font_descent = {descent};",
        "",
        "const wr_glyph wr_font_glyph[WR_N_GLYPHS] = {",
    ]
    for ch, ax, ay, w, h, bx, by, adv in placed:
        name = {" ": "space", EM_DASH: "em-dash", chr(92): "backslash"}.get(ch, ch)
        lines.append(f"    {{{ax:4d},{ay:4d},{w:3d},{h:3d},{bx:4d},{by:4d},{adv:3d}}},"
                     f"  // {name}")
    lines.append("};")
    lines.append("")
    lines.append("const uint8_t wr_font_atlas[] = {")
    for i in range(0, len(data), 24):
        lines.append("    " + "".join(f"{b:4d}," for b in data[i:i + 24]))
    lines.append("};")
    lines.append("")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines))

    non_empty = sum(1 for p in placed if p[3])
    print(f"font    {Path(args.font).name} @ {args.size}px  ascent={ascent} descent={descent}")
    print(f"atlas   {atlas_w}x{atlas_h} = {len(data):,} B, {non_empty}/{len(CHARS)} glyphs drawn")
    print(f"advance 'n'={font.getlength('n')}  'M'={font.getlength('M')}")
    print(f"        -> {args.out} ({args.out.stat().st_size:,} B of C)")

    preview = REPO / "build" / "font_atlas.png"
    preview.parent.mkdir(exist_ok=True)
    atlas.save(preview)
    print(f"        atlas preview: {preview}")


if __name__ == "__main__":
    main()
